# NXOS Jinja2 Template Configuration File
#
# Author: Matt Oswalt (http://keepingitclassless.net)
#
# This configuration file houses all of the dymanically populated information
# that makes it's way into an NXOS configuration script through Jinja2
# templates.
#
# Refer to the README for more details on how to use this tool.

# CORESNIPPETS
#
# These are the core snippets needed to build a basic, 
# switch-agnostic configuration.
coresnippets:
    - features
    - vlans
    - qos
    - ports
    - misc

# FEATURES
#
# Enables features on the switch
# Currently using actual NXOS feature syntax, this may change in future
features:
    - feature fcoe
    - install feature-set fabricpath
    - feature-set fabricpath
    - feature npiv
    - feature fport-channel-trunk
    - feature tacacs+
    - cfs eth distribute
    - feature udld
    - feature interface-vlan
    - feature lacp
    - feature vpc
    - feature lldp


# VLANS
#
# Defines the VLANs and their corresponding names/descriptions that should be
# placed on the switch.
#
# Format is a key/value pair, where VLAN ID is the key, and name/description is
# the corresponding value.
#

vlans:
    109: Core_Services_10.1.9.0/24
    232: 1000v-Control_10.1.32.0/23
    234: CIFS_10.1.34.0/24
    235: FCoE-Fabric-A
    240: ESX_MGMT_10.1.40.0/24
    241: vMotion_10.1.41.0/24
    249: Corporate-VMs_10.1.49.0/24
    260: NFS_10.1.160.0/20
# QOS
#
# Specifies some parameters to be used in a standard MQC-style configuration
qos:
    defaultmtu: 1500 # The MTU to be used on class-default 
                     # (unclassified) traffic

# PORTS
#
# Specifies general configuration settings for individual ports. Many ports 
# receive more specific configuration as part of the "feature installation"
# option in future versions, but this is a handy way to make en masse changes
# first.
ports:
    trunks:
        "e1/1-48" 
        #TODO: need to make this not a simple string - probably a list

# MISC
#
# This section contains various portions of the configuration that don't 
# deserve their own section. Because they're stupid, that's why.
misc:
    hostname: "N5K-A"
    mgmtgw: 10.1.1.1
    ntp: 
        - 192.168.11.10
        - 192.168.11.11
    snmp:
        traphost: 10.102.2.100


